# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_SecondWeek_Seminar_Assignment1_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_SecondWeek_Seminar_Assignment1_Login

  target 'iOS_SecondWeek_Seminar_Assignment1_LoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_SecondWeek_Seminar_Assignment1_LoginUITests' do
    # Pods for testing
  end

end
